### ISSUE TITLE
Track Disk I/O Utilization

### ISSUE THREAD

**Issue by elgalu** [labmlai/labml#64]
Thanks for this great project! it would be possible to also monitor/track disk I/O utilization?

**Comment by vpj** [comment]
Thanks for the complements.

We had disk IO (https://psutil.readthedocs.io/en/latest/#psutil.disk_io_counters) for a brief period and removed it because monitoring we thought it was not important model training. Out of curiosity why do you monitor it and what sort of insights do you get out of it?

@hnipun is rewriting part of our app to handle more traffic. We will add io counters as soon as thats done. This will need changes to both our client library (this repo) and the app.

**Comment by elgalu** [comment]
Cool! I wanted to compare different disk types in AWS and though of including I/O metrics.
