### ISSUE TITLE
500 Error Issue

### ISSUE THREAD

**Issue by Ananya-Joshi** [labmlai/labml#80]
Hi, 

I see this error "Oops! Something went wrong 500 Seems like we are having issues right now". 

I'm also unable to run the app locally. Please advise. 

labml app-server gives me: labml: error: argument command: invalid choice: 'app-server' (choose from 'dashboard', 'capture', 'launch', 'monitor', 'service', 'service-run')

**Comment by nmasnadithya** [comment]
Hi @Ananya-Joshi,

Thanks for opening an issue. The issue with the hosted instance should be resolved now. 

I don't recommend using the hosted instance for anything other than doing basic tests of the platform. Due to the fact that there can be some outages due to high loads. We are not actively scaling our servers currently (due to high server costs).

**Comment by nmasnadithya** [comment]
Please check and upgrade the `labml` pip package on your local machine. I highly suspect that's the reason behind the error when you are running locally.

**Comment by Ananya-Joshi** [comment]
Thank you! Of course, that makes sense. I really enjoyed using the product otherwise.
